apps/articles/urls.py
from django.conf.urls.defaults import patterns, url
from django.conf import urls

urlpatterns = patterns('',  
  
    #json for datatables
    url(r'^articles/list/json/$', 'apps.articles.views.list_articles_json', name='list_articles_json'),
    url(r'^articles/list/(?P<tags>(.+)(,\s*.+)*)/json/$', 'apps.articles.views.list_articles_json', name='list_articles_json'),  
    url(r'^user/(?P<user_id>\d*)/(?P<tags>(.+)(,\s*.+)*)/json/$', 'apps.articles.views.list_articles_json', name='list_articles_json'),
    url(r'^articles/tag/(?P<tags>(.+)(,\s*.+)*)/json/$', 'apps.articles.views.list_articles_json', name='list_articles_json'),    

    # Return all articles
    url(r'^articles/list/$', 'apps.articles.views.read_article', name='read_article'),    
    
    # Return a single article
    url(r'^articles/read/(?P<id>\d*)/$', 'apps.articles.views.read_article', name='read_article'),    
    
    # Create
    url(r'^articles/create/$', 'apps.articles.views.create_article', name='create_article'),    
    url(r'^articles/tag/(?P<tags>(.+)(,\s*.+)*)/$', 'apps.articles.views.search_article', name='search_article'),

    #Ajax APIs
    url(r'^articles/(?P<id>\d*)/body/form/$', 'apps.articles.views.ajax_article_body_form', name='ajax_article_body_form'),
    url(r'^articles/(?P<article_id>\d*)/comments/$', 'apps.articles.views.ajax_comments_article', name='ajax_comments_article'),

    #User url articles
    #url(r'^user/(?P<user_id>\d*)/articles/tag/(?P<tags>(.+)(,\s*.+)*)/$', 'apps.articles.views.search_article', name='read_user_articles'),

    url(r'^user/(?P<user_id>\d*)/article/(?P<id>\d*)/$', 'apps.articles.views.read_article', name='read_user_article'),  
    url(r'^user/(?P<user_id>\d*)/(?P<tags>(.+)(,\s*.+)*)/$', 'apps.articles.views.search_article', name='read_user_articles'),
    
    # Comment articles
    url(r'^articles/(?P<article_id>\d*)/comment/$', 'apps.articles.views.comment_article', name='comment_article'),
  

    
)

urls.py
from django.conf.urls.defaults import patterns, include, url
from django.conf import settings

from django.contrib import admin
admin.autodiscover()


# Resoures
from apps.mobile.api import UserResource
from apps.mobile.api import ChatEntryResource
from apps.mobile.api import ForumThreadResource
from tastypie.api import Api

v1_api = Api(api_name='v1')
#v1_api.register(UserResource())
v1_api.register(ChatEntryResource())
v1_api.register(ForumThreadResource())

urlpatterns = patterns('',
    (r'^api/', include(v1_api.urls)),
)

urlpatterns += patterns('',
    url(r'^admin/', include(admin.site.urls)),
    (r'^mobile/', include('apps.mobile.urls')),
    (r'^', include('apps.registration.urls')),
    (r'^', include('apps.frontpage.urls')),
    (r'^', include('apps.core.urls')),
    (r'^', include('apps.settings.urls')),
    (r'^', include('apps.guestbook.urls')),

    (r'^forum/', include('apps.forum.urls')),
    (r'^user/', include('apps.profiles.urls')),
    (r'^chat/', include('apps.chat.urls')),
    (r'^claim/', include('apps.claim.urls')),
    (r'^notifications/', include('apps.notifications.urls')),
    (r'^', include('apps.articles.urls')),
    (r'^accounts/', include('apps.accounts.urls')),
)

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += patterns('',
        (r'^(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}))

apps/articles/models.py
# -*- coding: utf-8 -*-

import datetime

from django.db import models
from django.contrib.auth.models import User
from django.contrib.humanize.templatetags.humanize import naturalday
from django.core.urlresolvers import reverse
from django.template.loader import render_to_string


from mptt.models import MPTTModel
from mptt.models import TreeForeignKey
from mptt.models import TreeManager

import site_strings
from apps.core.managers import TaggableManager
from apps.core.templatetags.entry_tags import render_tag
from apps.core.models import Entry
from apps.core.signals import *

class Article(Entry):
    """
    Articles

    """
    title = models.CharField(max_length=128, verbose_name="Rubrik")
    body = models.TextField(max_length=5120, verbose_name="Text", help_text = site_strings.COMMENT_FORM_HELP_TEXT)
    tags = TaggableManager(verbose_name="Kategorier")
    allow_comments = models.NullBooleanField(default=False,verbose_name="Tillåt kommentarer")

    class Meta:
        verbose_name = "Artikel"
        verbose_name_plural = "Artiklar"

    def __unicode__(self):
        return u''.format( self.title )

    @property
    def get_verbose_name(self):
        return self._meta.verbose_name

    def tags_list(self):
        if not hasattr(self, "_cached_tags"):
            self._cached_tags = self.tags.all()
        return self._cached_tags

    @property
    def ajax_editable_fields(self):
        return ["body", "allow_comments"]

    @property
    def is_deleteble(self):
        return True
        
    @property
    def delete_next_url(self):
        return reverse('read_article')
        
    @property
    def is_editable(self):
        """
        Limit is_editable to one day
        """
        return datetime.datetime.now() - self.date_created < datetime.timedelta(days=1)
           
    @property
    def allow_history(self):
        return True    
        
    @property
    def fields_history(self):
        return ["body"]

    def get_absolute_url(self):
        return "/articles/read/%s/" % self.id

    def get_absolute_url(self):
        return u"{0}".format( reverse('read_article', args=[self.id]) )
    
    def __unicode__(self):
        return u'%s' % self.title

    @property
    def verbose_name(self):
        return u'artikel'
        
    def aaData(self, request):
        """
        aaData formats for datatables
        """
        subscriptions=request.user.profile.subscriptions.all()
        tags = ""
        for tag in self.tags.all():
            vars = render_tag(tag, '/forum/tag/', subscriptions)
            tags += render_to_string('tag_template.html', vars)

        title = u"<a href=\"{0}\" >{1}</a>".format( self.get_absolute_url(), self.title )
        created = u"{0} {1} av <a href=\"{2}\">{3}</a>".format(naturalday(self.date_created), self.date_created.strftime("%H:%M"), self.created_by.get_profile().get_absolute_url(), self.created_by.username)

        if self.allow_comments:
            allow_comments = self.get_posts_index()
        else:
            allow_comments = "-"

        data =  {
                'title': title,
                'created': created,
                'tags' : tags,
                'allow_comments': allow_comments,
                'id': self.id,
                }

        return data
    
    def get_posts_index(self):   
        return ArticleComment.objects.filter(post=self).count()
        
class ArticleComment(MPTTModel):
    """ Threaded comments for blog posts """
    post = models.ForeignKey(Article)
    author = models.CharField(max_length=60)
    created_by = models.ForeignKey(User, related_name="created_%(class)s_entries", blank=True, null=True)
    comment = models.TextField(max_length=5120, help_text=site_strings.COMMENT_FORM_HELP_TEXT, verbose_name="Kommentar")
    added  = models.DateTimeField(default=datetime.datetime.now,blank=True)
    date_last_changed = models.DateTimeField(auto_now=False, blank=True, null=True)
    
    tags = TaggableManager()
    objects = tree = TreeManager()

    # a link to comment that is being replied, if one exists
    parent = TreeForeignKey('self', null=True, blank=True, related_name='children')
    
    class Meta:
        verbose_name = "Artikelkommentar"
        verbose_name_plural = "Artikelkommentarer"

    class MPTTMeta:
        # comments on one level will be ordered by date of creation
        order_insertion_by=['added']
        
    def __unicode__(self):
        return u'Svar på "{0}"'.format( self.post.title )

    @property
    def get_verbose_name(self):
        return self._meta.verbose_name

    @property
    def ajax_editable_fields(self):
        return ["comment"]

    @property
    def is_deleteble(self):
        
        deleteble = False
        
        if self.is_root_node():
            deleteble = True
        
        if not self.is_leaf_node():
            deleteble = False
            
        if not self.is_root_node():
            siblings = self.get_siblings(include_self=True).reverse()
            siblings_count = len (siblings)
            
           # If not alone?
            if siblings_count > 1:
                deleteble = False 

            #If last? 
            if siblings[0] == self:
                deleteble = True

        return deleteble
        
    @property
    def is_editable(self):
        """
        Limit is_editable to one day
        """
        return datetime.datetime.now() - self.added < datetime.timedelta(days=1)
           
    @property
    def allow_history(self):  
        return True    
        
    @property
    def fields_history(self):
        return ["comment"]

    def get_absolute_url(self):
        return "{0}?h=comment-{1}".format( reverse('read_article', args=[self.post.id]), self.id )
        
    @property
    def get_reply_url(self):
        return reverse('comment_article', args=[self.post.id])

class defaultArticleCategories(models.Model):
    """
    Default categories for articles
    using tags
    """
    tags = TaggableManager()

    def __unicode__(self):

        text = self.tags.all()[0]

        return u'%s' % (text)
        

class ModeratorArticleCategories(models.Model):
    """
    Default categories for the articles
    for moderators, using tags
    """
    tags = TaggableManager()

    def __unicode__(self):

        text = self.tags.all()[0]

        return u'%s' % (text)

apps/articles/forms.py
# -*- coding: utf-8 -*-
from models import *
from django import forms
from django.forms import ModelForm, Textarea, HiddenInput, CheckboxInput
from django.forms.fields import MultipleChoiceField
from apps.core.widgets import CheckboxSelectMultiple

import site_strings

from taggit.forms import *

DEFAULT_CATEGORIES = ( (tag, unicode( tag ).title() ) for tag in defaultArticleCategories.objects.all() )

class DefaultArticleTagsForm(forms.Form):
    default_tags = forms.MultipleChoiceField(
        required=True,
        widget=CheckboxSelectMultiple(attrs={'class':'ui-toggle-button'}),
        choices=DEFAULT_CATEGORIES,
        label="Huvudkategorier",
    )
    
class ArticleForm(ModelForm):
    """
    Form for articles

    """    

    tags = TagField(
        required=False,
        error_messages={
            'required': 'Du har inte angett någon kategori!',
        },
        widget=TagWidget(attrs={'placeholder': 'Egna kategorier, separera dem med kommatecken (,)'}),
        label="Egna kategorier",
        help_text="Separera kategorier med kommatecken. Kategorier med flera ord skrivs inom fnuttar."
    )

    user_tags = forms.MultipleChoiceField(
        required=False,
        widget=CheckboxSelectMultiple(),
        choices=DEFAULT_CATEGORIES,
        label="Egna bevakade kategorier",
    )

    def __init__(self, *args, **kwargs):
        
        user = kwargs.pop('user', None)

        super(ArticleForm, self).__init__(*args, **kwargs)
        if user is not None:
            subscriptions =  user.profile.subscriptions.all()
            subscriptions_choices = ( (tag, unicode( tag ).title() ) for tag in subscriptions )
            self.fields['user_tags'].choices = subscriptions_choices

    class Meta:
        model = Article
        fields = ('user_tags','tags','title','body','allow_comments',)
        widgets = {
                    'title': forms.TextInput(attrs={'placeholder': "Ange en titel"}),
		            'body': Textarea(attrs={'cols': 80, 'rows': 5, 'placeholder': "Minst fem tecken."}),
                    'allow_comments':CheckboxInput(),
                   }
        
 
class ArticleBodyForm(ModelForm):

    class Meta:
        model = Article
        fields = ('body',)

        body = forms.CharField(label="", help_text="", widget=forms.Textarea())

class ArticleCommentForm(ModelForm):
    comment = forms.CharField(label="", widget=forms.Textarea(), help_text=site_strings.COMMENT_FORM_HELP_TEXT)

    class Meta:
        model = ArticleComment
        fields = ('comment',)

apps/articles/templates/_article_comments.html
{% load mptt_tags %}
{% load markup %}
{% load humanize %}
{% load thumbnail %}
{% load entry_tags %}
{% load filters %}

<form id="comment-article-form" method="POST" action="{% url comment_article article.id %}">
    {% csrf_token %}
    {% for field in ArticleBodyForm %}
    {{ field }}
    {% endfor %}
    <input type="hidden" name="parent_id" value="">
    
    <div class="buttonset">
        <input type="submit" value="Kommentera">
        <input type="button" data-preview="comment" value="Förhandsgranska" />
    </div>

</form>

<ul class="flat-list entrylist">
    {% recursetree comments %}
    <li id="comment-{{ node.id }}" class="entry ui-widget ui-widget-content">

        {% render_entry node request %}
        
        {# recursion! children of a given comment #}
        
        {% if not node.is_leaf_node %}
            <ul class="flat-list child-ul entrylist">
            
            {{ children }}
    
            <li class="accordion">
                <h4 class="ui-widget-header entry-head">
                    <a href="#">Fortsätt på tråden</a>
                </h4> 
                              
                <div class="clearfix">
                    <form method="POST" action="{% url comment_article article.id %}">
                        {% csrf_token %}
                        <textarea name="comment"></textarea>
                        <input type="hidden" name="parent_id" value="{{ node.id}}">
                        <div class="buttonset">
                            <input type="submit" value="Svara">
                            <input type="button" data-preview="comment" value="Förhandsgranska" />
                        </div>
                    </form>
                </div>
            </li>
            
            </ul>
        {% endif %}
        
    </li>
    {% endrecursetree %}
</ul>

apps/articles/templates/_comments.html
{% load mptt_tags %}
{% load markup %}
{% load humanize %}
{% load thumbnail %}
{% load entry_tags %}
{% load filters %}
{% load notification_tags %}

<div data-article-id="{{ article_id }}" class="ui-widget ui-widget-content ui-widget-padded ui-helper-clearfix form-wrapper">
    <form data-container="comments-{{article_id}}" id="comment-article-{{ article_id }}-form" class="form-add-entry" method="POST" action="{{ post_url }}">
        {% csrf_token %}
        <input type="hidden" name="parent_id" value="">
        <ul>
            {{ commentform.as_ul }}
            <li class="buttonpanel">
                <div class="buttonset">
                    <input type="submit" value="Kommentera">
                    <input type="button" data-preview="comment" value="Förhandsgranska" />
                    <input type="button" data-field="comment" data-maximize="true" data-form="comment-article-{{ article_id }}-form" value="Storskärm" />
                </div>
                <div class="buttonset">
                    <input type="checkbox" class="toggle-rel-threads" id="toggle-rel-threads-{{ article_id }}" /><label class="toggle-rel-threads" for="toggle-rel-threads-{{ article_id }}">Visa enbart relevanta trådar</label>
                </div>
            </li>
        </ul>
    </form>
</div>

<ul class="comment-list ui-helper-reset">
{% recursetree comments %}
	{% get_notes_for_item node request.user as node %}

    <li class="ui-helper-reset">
        <!-- Kommentar -->
        <div data-comment-id="{{ node.id }}" id="comment-{{ node.id }}" class="{% if node.notification and node.notification.status < 3 %}ui-state-highlight{% endif %} ui-widget ui-widget-content ui-helper-clearfix comment-entry comment-entry-mouseout">

            <h4 class="ui-widget-toolbar ui-helper-reset header clearfix">
                {% render_userlink node.created_by %} {{ node.added }} {% if node.notification %}<em>({{node.notification.get_status_display}})</em>{% endif %}

                <div class="button-wrapper buttonset">
                    {% if node.date_last_changed %}
                    <a href="{% url history_entry app_name model_name node.id %}" data-article-id="{{ article_id }}" class="js-entry-history">&nbsp;</a>
                    {% endif %}

                    {% if node.is_deleteble and node.created_by == request.user %}
                    <a href="{% url delete_entry app_name model_name node.id %}" data-article-id="{{ article_id }}" data-comment="comment-{{ node.id }}" class="js-entry-delete">&nbsp;</a>
                    {% endif %} 

                    {% if node.is_editable and node.created_by == request.user %}
                    <a href="{% url update_entry app_name model_name node.id %}" data-article-id="{{ article_id }}" class="js-entry-edit" rel="comment-{{ node.id }}-content">&nbsp;</a>
                    {% endif %}
                </div>
            </h4>

            <div class="clearfix">
                {% if node.created_by.profile.photo %}
                <div class="photo">    
                    {% thumbnail node.created_by.profile.photo "50x50" crop="center" as im %}
                    <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" alt="{{ node.created_by }}">
                    {% endthumbnail %}
                </div>
                
                <div class="photo-padding content">
                {% else %}            
                <div class="content">
                {% endif %}
                
                    <div>
                        <div id="comment-{{ node.id }}-content">
                            {{ node.comment|user_filter }}
                        </div>
                    </div>
                </div>
            </div>

            <h4 class="ui-widget-toolbar ui-helper-reset footer clearfix" style="text-align:left;">
                <div class="button-wrapper buttonset" style="float:left;">
                    {% if not node.is_root_node %}
                    <a href="#" data-form="comment-article-{{ article_id }}-form" data-comment="comment-{{ node.id }}" class="js-reply-all">&nbsp;Svara i tråden</a>
                    {% endif %}

                    {% if children %}
                    <a href="#" data-form="comment-article-{{ article_id }}-form" data-comment="comment-{{ node.id }}" data-has-children="comment-{{ node.id }}" class="js-reply-all">&nbsp;Svara</a>
                    {% else %}
                    <a href="#" data-form="comment-article-{{ article_id }}-form" data-comment-id="{{ node.id }}" data-comment="comment-{{ node.id }}" class="js-reply">&nbsp;Svara i ny subtråd</a>
                    {% endif %}
                </div>
            </h4>

        </div>
        <!-- /Kommentar -->

        {% if children %}
        <ul class="list-comments ui-helper-reset">
        {{ children }}
        </ul>
        {% endif %}
    </li>
{% endrecursetree %}
</ul>

apps/articles/templates/article.html
{% extends "base.html" %}
{% load entry_tags %}
{% load thumbnail %}
{% load markup %}    
{% load humanize %}
{% load filters %}
{% load pagination_tags %}

{% block content %}
<ul class="flat-list">


<li class="ui-widget ui-widget-content article-entry" id="article-{{article.id}}">
	<h4 class="ui-widget-header ui-helper-reset header {% if article.notification and article.notification.status < 3 %}ui-state-active{% endif %}"> {{ article }} av {% render_userlink article.created_by %} - {{ article.date_created }} 
	
 		<div class="tag-wrapper">
	    	{% with subscriptions=request.user.profile.subscriptions.all %}
		    {% for tag in article.tags.all %}
		    {% render_tag tag tag_search_prefix subscriptions %}
		    {% endfor %}
			{% endwith %}
		</div>

		<div class="button-wrapper buttonset">
			{% if article.allow_history and article.date_last_changed %}
				<a href="{% url history_entry app_name "article" article.id %}" data-article-id="{{ article_id }}" class="js-entry-history">&nbsp;</a>
            {% endif %}

			{% if article.is_editable and article.created_by == request.user %}
        		<a href="{% url update_entry app_name "article" article.id %}" data-article-id="{{ article.id }}" class="js-entry-edit" rel="content-{{ article.id }}">&nbsp;</a> 
        	{% endif %}

			{% if article.is_deleteble and article.created_by == request.user %}
				<a href="{% url delete_entry app_name "article" article.id %}" data-next-url="{% url read_article %}" data-article-id="{{ article.id }}" data-comment="" class="js-entry-delete">&nbsp;</a>
			{% endif %} 
		</div>

	</h4>

	{% if article.created_by.profile.photo %}
	<div class="entry-profile">    
	    {% thumbnail article.created_by.profile.photo "75x75" crop="center" as im %}
	    <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
	    {% endthumbnail %}
	</div>
	{% endif %}

	<div class="entry-content clearfix">
	    <div id="content-{{ article.id }}" class="content">
	        {{ article.body|user_filter }}
	    </div>
	</div>

	<div class="ui-widget-toolbar footer">
		<div class="buttonpanel">
	       	<div class="buttonset">
				<button class="ui-helper-hidden btn-comment-article" data-container="comments-{{article.id}}" data-form="comment-article-{{ article.id }}-form" id="btn-comment-{{ article.id }}">Svara</button>
			</div>
       </div>
	</div>

</li>

{% if article.allow_comments %} 
<li class="cont-comments ui-widget ui-widget-content " id="comments-{{article.id}}">
{% url comment_article article.id as post_url %}
{% include "_comments.html" with article_id=article.id app_name="articles" model_name="ArticleComment" post_url=post_url %}
</li>
{% endif %}

</ul>

{% endblock content %}










{% comment %}
{% extends "articles.html" %}
{% load entry_tags %}

{% block content %}
<ul class="flat-list">    
    <li class="ui-widget ui-widget-content">
        {% render_entry article request %}
    </li>
</ul>

{% if article.allow_comments %}
{% include "_article_comments.html" %}
{% endif %}

{% endblock content %}
{% endcomment %}

apps/articles/templates/articles.html
{% extends "base.html" %}
{% load entry_tags %}
{% load thumbnail %}
{% load humanize %}

{% block app_navigation %}
<ul id="app_navigation" >
    <li><h4 class="ui-widget-header ui-helper-reset" >Artikelmeny</h4></li>
    <li><a href="{% url read_article %}">Alla artiklar</a></li>
    <li><a href="{% url create_article %}">Skriv ny</a></li>
    <li><h4 class="ui-widget-header ui-helper-reset" >Huvudkategorier</h4></li>
    
    {% for tag in categories %}
    <li><a href="{% url search_article tag %}">{{ tag|title }}</a></li>
    {% endfor %}
</ul>
{% endblock app_navigation %}

{% block content %}   

<div id="tabs">
    <ul>
        <li><a href="#tabs-1">Artiklar</a></li>
        {% if notes %}<li><a href="#tabs-2">Notifieringar <span id="tab-counter-notes">({{ notes|length }})</span></a></li>{% endif %}
    </ul>
    
    <div id="tabs-1">         
        <table id="table_articles"  class="articles_table">
            <thead>
                <tr>
                    <th>Titel</th>
                    <th>Skapad</th>
                    <th>Kategorier</th>
                    <th>Kommentarer</th>
                    <th>ID (sortering)</th>
                </tr>
            </thead>
            <tbody>
                    <td>Läser in artiklar...</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
            </tbody>
        </table>
    </div>


    {% if notes %}
    <div id="tabs-2">
        {% for notification in notes %}
        {% if forloop.first %}
        <table id="notification_table" class="articles_table">
            <thead>
                <tr>
                    <th>Artikel</th>
                    <th>Status</th>
                    <th>Tid</th>
                    <th>Från</th>
                    <th>Ta bort</th>
                    <th>ID (Sortering)</th>
                </tr>
            </thead>
            <tbody>
        {% endif %}
                <tr class="ui-widget-content">
                    <td><a href="{{ notification.instance_url }}">{{ notification.message }}</a></td>
                    <td>{{ notification.get_status }}</td>
                    <td>{{ notification.date_created|naturalday  }} {{ notification.date_created|time:"TIME_FORMAT"  }}</td>
                    <td><a href="{{ notification.sender.get_profile.get_absolute_url }}">{{ notification.sender }}</a></td>
                    <td>
                        <form  class="ajax-delete-note" action="{% url delete_notification %}" method="post" >
                        {% csrf_token %}
                        <input type="hidden" value="{{ notification.id }}" id="id-{{ notification.id }}" name="notification_id" >
                        <input class="button-mark" value="Ta bort" type="submit" id="input-delete-{{ notification.id }}" />
                        </form>
                    </td>
                    <td>{{ notification.id }}</td>
                </tr>
        {% if forloop.last %}
            </tbody>
        </table>
        {% endif %}

        {% empty %}
        <h2>Inga notifieringar</h2>
        {% endfor %}
    </div>
    {% endif %}
</div>
{% endblock content %}

apps/articles/templates/create_article.html
{% extends "articles.html" %}

{% block content %}
<div class="ui-widget">
    <h2 class="ui-widget-header ui-helper-reset">Skapa ny Artikel</h2>

    <form class="ui-widget-content" action="{% url create_article %}" method="post" id="articles-form-create">
        
        <label>Du kan välja upp till 5 kategorier, minst en en huvudkategori</label>

        {% csrf_token %}
        <p>
            <label for="id_title">Huvudkategorier:</label>
                {% for field in tagform %}
                {{ field.errors }}
                {{ field }}
                {% endfor %}
        </p>

        {% for field in form %}
        <p id="field-wrapper-{{ field.name }}">    
            <label>{{ field.label }}:</label>
            {{ field.errors }}
            {{ field }} <span class="helptext">{{ field.help_text|safe }}</span>
        </p>
        {% endfor %}
        <br />
        <div class="ui-widget-toolbar">
            <div class="buttonset">
                <input type="submit" value="Skapa" />
                <input type="button" data-preview="body" value="Förhandsgranska" />
                <input type="button" data-maximize="true" data-form="articles-form-create" data-field="body" value="Storskärm" />

            </div>
        </div>
    </form>

</div>



{% comment %}

{% block content %}
    <h1>Skapa ny Artikel</h2>
    <form id="form-create-article" action="" method="post">
        {% csrf_token %}
        
        <h3>Du kan välja upp till 5 kategorier, minst en en huvudtagg</h3>
        <div class="tag-list-wrapper">       
        {% for field in tagform %}
        {{ field }}
        {% endfor %}
        
        </div>

        <p>
        {{ form.tags }}
        </p>
        
        <p>
        {{ form.title }}
        </p>
        
        <p>
        {{ form.body }}
        </p>
        
        <p>           
        {{ form.allow_comments }}<label for="id_allow_comments">Tillåt kommentarer</label>
        </p>

        <div class="buttonset">
            <input type="submit" value="Skapa" />
            <input type="button" data-preview="body" value="Förhandsgranska" />
        </div>
    </form>

{% endcomment %}

{% endblock content %}

apps/articles/templates/user_article.html
{% extends "profile.html" %}
{% load entry_tags %}

{% block content %}
<ul class="flat-list entrylist">    
    <li class="ui-widget ui-widget-content acticle_post"> 
        {% render_entry article request %}
    </li>
</ul>

{% if article.allow_comments %}
{% include "_article_comments.html" %}
{% endif %}

{% endblock content %}

apps/articles/templates/user_articles.html
{% extends "profile.html" %}
{% load entry_tags %}
{% load thumbnail %}
{% load humanize %}

{% block content %}
<table id="table_articles"   class="articles_table ui-widget ui-widget-content">
    <thead>
        <tr>
            <th>Titel</th>
            <th>Skapad</th>
            <th>Kategorier</th>
            <th>Kommentarer</th>
            <th>ID (sortering)</th>
        </tr>
    </thead>
    <tbody>
            <td>Läser in artiklar...</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
    </tbody>
</table>
{% endblock content %}